### ISSUE TITLE
Improve first user experience

### ISSUE THREAD

**Issue by Adafede** [JuBiotech/peak-performance#31]
Dear @Y0dler, and @michaelosthege 

I have been assigned to review your repository for https://github.com/openjournals/joss-reviews/issues/7313.

As this is my first issue, please be ensured I highly appreciate **a lot** of points that are already available. Per convenience, I will not list all the things that are already done well, but only the "issues" so this might give a way more negative impression than what my real thoughts are, my apoogies for it already!

- [x] Add link to the automatically generated documentation as repository link in the "about" section
- [x] The README does not contain much and directly redirects to the doc. The very basic initial steps should be in there, more or less like the first page of the doc.
- [x] Admitting a user does not want to install the software using pip, are there other alternatives? Could alternative installations (poetry, mamba, ...) be made available for users? Oh... this was answered on the next page, probably some other lazy users will also not want to get to page 2 to read if they can install it without using pip?
- [x] Provide a full example for https://peak-performance.readthedocs.io/en/latest/markdown/Preparing_raw_data.html#preparing-raw-data and not let users have to create lists for time and intensity on their own?

**Comment by Y0dler** [comment]
By basic steps, do you refer just to the installation instructions?  
  
I updated the about section with the link to the documentation and changed the landing page of the docu to contain all installation instructions in a new PR.

**Comment by Adafede** [comment]
Yes, you adressed everything except the example time and intensity arrays in #35  😊

**Comment by Y0dler** [comment]
Just replaced the markdown file with a Jupyter notebook which shows how to open a `*.npy` file (although I guess this was also covered in some of the other notebooks) and then gives an example of an actual metabolite and a random time series showing how the file would have to be named and how it can be stored. Is this sufficient?

**Comment by Adafede** [comment]
@Y0dler Perfect, it will probably help a lot of beginners 😉

**Comment by Adafede** [comment]
I let you merge and close 👍🏼
